# These are supported funding model platforms

github: xqwtxon # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: xqwtxon # Replace with a single Patreon username
open_collective: xqwtxon # Replace with a single Open Collective username
ko_fi: xqwtxon # Replace with a single Ko-fi username
custom: https://xqwtxon.ml # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
